[project]
name = "mcpcrashcourse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain-groq>=0.3.7",
    "mcp-use>=1.3.9",
    "mcp[cli]>=1.12.4",
]
